config/routes.rb
Rails.application.routes.draw do
  
  namespace :backend do
    resources :sub_categories, except: [:show, :destroy]
    resources :categories, except: [:show, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins

  get 'dashboard/index'

  root "dashboard#index"

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :description, presence: true
  paginates_per 5

  has_many :sub_categories
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :region
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
  paginates_per 5
  validates :description, presence: true
  validates :category, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/backend/categories_controller.rb
class Backend::CategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_category, only: [:edit, :update, :destroy]
  before_action :get_categories, only: [:new, :edit, :index, :create]
  layout 'backend'
  def index
    @categories = Category.order(:description).page params[:page]
  end
  def new
    @category = Category.new
  end
  def create
    @category = CategoryService.create(params_category)
    unless @category.errors.any?
      redirect_to backend_categories_path, notice: "#{@category.description} was created!"
    else
      render :new
    end
  end
  def edit
    #code
  end
  def update
    if @category.update(params_category)
      redirect_to backend_categories_path, notice: "#{@category.description} updated with success!"
    else
      render :edit
    end
  end
  def destroy
    #code
  end

  private

  def set_category
    @category = Category.find_by(id: params[:id])
  end

  def get_categories
    @categories = Category.all
  end

  def params_category
    params.require(:category).permit(:description, :status)
  end
end

app/controllers/backend/categories_controller/category_service.rb
class Backend::CategoriesController::CategoryService
  attr_accessor :category
  def self.create(params_category)
    @category = Category.new(params_category)
    if @category.valid?
      @category.save
    end
    @category
  end
end

app/controllers/backend/sub_categories_controller.rb
class Backend::SubCategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :get_subcategories
  before_action :set_sub_categories, only: [:edit, :update]
  before_action :get_categories

  layout 'backend'
  def index
    @subcategories = SubCategory.order(:category_id).page params[:page]
  end
  def new
    @subcategory = SubCategory.new
  end
  def create
    # call service subcategories
    @subcategory = SubCategoryService.create(params_subcategory)
    unless @subcategory.errors.any?
      redirect_to  backend_sub_categories_path, notice: "Sub category #{@subcategory.description} was created with success!"
    else
      render :new
    end
  end
  def edit
    #code
  end
  def update
      if @subcategory.update(params_subcategory)
        redirect_to backend_sub_categories_path, notice: "Sub category #{@subcategory.description} was updated with success!"
      else
        render :edit
      end
  end

  private
  def get_categories
    @categories = Category.all
  end
  def get_subcategories
    @subcategory = SubCategory.order(:category_id)
  end
  def set_sub_categories
    @subcategory = SubCategory.find_by(id: params[:id])
  end
  def params_subcategory
    params.require(:sub_category).permit(:description, :status, :category_id)
  end
end

app/controllers/backend/sub_categories_controller/sub_category_service.rb
class Backend::SubCategoriesController::SubCategoryService
  attr_accessor :sub_category
  def self.create(params_subcategory)
    @subcategory = SubCategory.new(params_subcategory)
    if @subcategory.valid?
      @subcategory.save
    end
    @subcategory
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_admin!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backend/categories_helper.rb
module Backend::CategoriesHelper
end

app/helpers/backend/sub_categories_helper.rb
module Backend::SubCategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/backend/categories/edit.html.erb
<%= render partial: "backend/categories/shared/form" %>

app/views/backend/categories/index.html.erb
<br  />
                <% if notice %>
                <script>
                  toastr.info('<%= notice %>')
                </script>
                <% end %>
                <div class="panel panel-primary">
                        <div class="panel-heading">
                            Listando Categorias
                            <%= link_to   new_backend_category_path  , :class => 'btn btn-success pull-right', :style => "margin-top:-6px;" do %>
                            <i class="fa fa-plus"></i>
                            <% end %>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Descrição</th>
                                            <th>Situação</th>
                                            <th>Ações</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                      <% @categories.each do |category| %>
                                        <tr>
                                            <td><%= category.id %></td>
                                            <td><%= category.description %></td>
                                            <% if category.status %>
                                            <td><p class="text-success"><%= "Ativada" %></p></td>
                                            <% else %>
                                            <td><p class="text-danger"><%= "Inativada" %></p></td>
                                            <% end %>
                                            <td>
                                            <%= link_to  edit_backend_category_path(category.id), class: "btn btn-warning btn-circle" do %>
                                            <i class="fa fa-check"></i>
                                            <% end %> | <button disabled type="button" class="btn btn-danger btn-circle"><i class="fa fa-times"></i>
                                              </button>
                                        </td>
                                        </tr>
                                        <% end %>
                                    </tbody>
                                </table>
                                <center><%= paginate @categories, theme: 'twitter-bootstrap-4',
                   pagination_class: "pagination-sm" %></center>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>

app/views/backend/categories/new.html.erb
<%= render partial: "backend/categories/shared/form" %>

app/views/backend/categories/shared/_form.html.erb
<br />
<% if @category.errors.any? %>
<% @category.errors.full_messages.each do |message| %>
<script>
  toastr.error('<%= message %>')
</script>
<% end %>
<% end %>

<div class="row">
  <div class="col-md-8">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= t('category') %></h3>
  </div>
  <div class="panel-body">
    <div class="col-lg-6">
      <%= form_for([:backend, @category]) do |f| %>
      <div class="form-group">
        <%= f.label :"Description" %><br/>
        <%= f.text_field :description, :class => 'form-control', :placeholder => 'Ex.: Animal / Pet' %><br />
        <%= f.label :"Status" %>
        <%= f.check_box :status %><br/><br />
        <%= f.submit t('buttons.save'), :class => 'btn btn-primary' %>
        <%= link_to t('buttons.back'),  backend_categories_path, :class => 'btn btn-warning'  %>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>
<div class="col-md-4">
  <div class="panel panel-info">
  <div class="panel-heading">Categories</div>
  <div class="panel-body">
    <% if @categories  %>
    <ul class="nav nav-pills nav-stacked nav-pills-stacked-example">
    <% @categories.each do |category| %>
      <% if category.status %>
      <li role="presentation" class="active">
      <%= link_to category.description,  edit_backend_category_path(category.id)  %>
      </li>
      <% else %>
      <li role="presentation">
      <%= link_to category.description,  edit_backend_category_path(category.id)  %>
      </li>
      <% end %>
    <% end %>
    </ul>
    <% end  %>
  </div>
</div>
</div>
</div>

app/views/backend/sub_categories/edit.html.erb
<%= render partial: 'backend/sub_categories/shared/form' %>

app/views/backend/sub_categories/index.html.erb
<br  />
                <% if notice %>
                <script>
                  toastr.info('<%= notice %>')
                </script>
                <% end %>
                <div class="panel panel-primary">
                        <div class="panel-heading">
                            Listando Sub Categories
                            <%= link_to    new_backend_sub_category_path   , :class => 'btn btn-success pull-right', :style => "margin-top:-6px;" do %>
                            <i class="fa fa-plus"></i>
                            <% end %>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Descrição</th>
                                            <th>Situação</th>
                                            <th>Categoria</th>
                                            <th>Ações</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                      <% @subcategories.each do |subcategory| %>
                                        <tr>
                                            <td><%= subcategory.id %></td>
                                            <td><%= subcategory.description %></td>
                                            <% if subcategory.status %>
                                            <td><p class="text-success"><%= "Ativada" %></p></td>
                                            <% else %>
                                            <td><p class="text-danger"><%= "Inativada" %></p></td>
                                            <% end %>
                                            <td><%= subcategory.category.description %></td>
                                            <td>
                                            <%= link_to   edit_backend_sub_category_path(subcategory.id), class: "btn btn-warning btn-circle" do %>
                                            <i class="fa fa-check"></i>
                                            <% end %> | <button disabled type="button" class="btn btn-danger btn-circle"><i class="fa fa-times"></i>
                                              </button>
                                            </td>
                                            <td></td>
                                      </tr>
                                        <% end %>
                                    </tbody>
                                </table>
                                <center><%= paginate @subcategories, theme: 'twitter-bootstrap-4',
                   pagination_class: "pagination-sm" %></center>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>

app/views/backend/sub_categories/new.html.erb
<%= render partial: 'backend/sub_categories/shared/form' %>

app/views/backend/sub_categories/shared/_form.html.erb
<br/>
<% if @subcategory.errors.any? %>
<% @subcategory.errors.full_messages.each do |message| %>
<script>
  toastr.error('<%= message %>')
</script>
<% end %>
<% end %>

<div class="row">
  <div class="col-md-8">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><%= t('subcategory') %></h3>
      </div>
      <div class="panel-body">
        <div class="col-lg-6">
          <%= form_for([:backend, @subcategory]) do |f| %>
          <div class="form-group">
            <%= f.label :"Description" %><br/>
            <%= f.text_field :description, :class => 'form-control', :placeholder => 'Ex.: Animal / Pet' %><br/>
            <%= f.label :"Status" %>
            <%= f.check_box :status %><br/><br/>
            <%= f.label :"Category" %><br/>
            <%= f.collection_select(:category_id, Category.all, :id, :description) %><br><br>
            <%= f.submit t('buttons.save'), :class => 'btn btn-primary' %>
            <%= link_to t('buttons.back'),   backend_sub_categories_path, :class => 'btn btn-warning'  %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-warning">
      <div class="panel-heading">Sub Categories</div>
      <div class="panel-body">
        <% if @categories  %>
        <ul class="nav nav-pills nav-stacked nav-pills-stacked-example">
          <% @categories.each do |category| %>
          <li role="presentation" class="active">
            <p class="text-primary">
              <a>{<%= category.description %>}</a>
            </p>
            <% category.sub_categories.each do |subcategory| %>
            <p class="text-success">---<%= subcategory.description %></p>
            <% end %>
          </li>
          <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<%= render partial: 'dashboard/shared/widgets' %>

app/views/dashboard/shared/_widgets.html.erb
<div class="row"><br><br>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-comments fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">26</div>
            <div>New Comments!</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right">
            <i class="fa fa-arrow-circle-right"></i>
          </span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-green">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-tasks fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">12</div>
            <div>New Tasks!</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right">
            <i class="fa fa-arrow-circle-right"></i>
          </span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-yellow">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-shopping-cart fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">124</div>
            <div>New Orders!</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right">
            <i class="fa fa-arrow-circle-right"></i>
          </span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-red">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-support fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">13</div>
            <div>Support Tickets!</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right">
            <i class="fa fa-arrow-circle-right"></i>
          </span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoloappBackend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <%= yield %>
      <!-- /#wrapper -->
    </div>
    <% if alert  %>
    <script>
      //$.notify("<%= alert %>", "error");
      toastr.info('<%= alert %>')
    </script>
    <% end %>
  </body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoloappBackend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="wrapper">

      <!-- Navigation -->
      <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html">Backend - Rolo</a>
        </div>
        <!-- /.navbar-header -->

        <%= render partial: "layouts/shared/header" %>

        <%= render partial: "layouts/shared/sidebar" %>
        <!-- /.navbar-static-side -->
      </nav>
      <div id="page-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
              <div class="col-lg-12"></div>
              
              <%= yield %>
            </div>
            <!-- /.col-lg-12 -->
          </div>
          <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
      </div>

      <!-- Page Content -->

      <!-- /#page-wrapper -->

    </div>

    <% if alert  %>
    <script>
      //$.notify("<%= alert %>", "error");
      toastr.info('<%= alert %>')
    </script>
    <% end %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoloappBackend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Backend - Rolo</a>
            </div>
            <!-- /.navbar-header -->

            <%= render partial: "layouts/shared/header" %>

            <%= render partial: "layouts/shared/sidebar" %>
            <!-- /.navbar-static-side -->
        </nav>
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <%= yield %>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>

        <!-- Page Content -->

        <!-- /#page-wrapper -->

    </div>

    <% if alert  %>
      <script>
          //$.notify("<%= alert %>", "error");
          toastr.info('<%= alert %>')
      </script>
    <% end %>
  </body>
</html>

app/views/layouts/shared/_header.html.erb
<ul class="nav navbar-top-links navbar-right">
  <li><%= current_admin.name %></li>
    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">

            <%= link_to destroy_admin_session_path, method: :delete do %>
            <i class="fa fa-sign-out fa-fw"></i> Logout
            <% end %>
            </li>
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
</ul>
<!-- /.navbar-top-links -->

app/views/layouts/shared/_sidebar.html.erb
<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse">
    <ul class="nav" id="side-menu">
      <li>
        <%= link_to dashboard_index_path do %>
        <i class="fa fa-dashboard fa-fw"></i>
        Panel
        <% end %>
      </li>

      <li class="">
        <a href="#">Category
          <span class="fa fa-list fa arrow"></span>
        </a>
        <ul style="height: 0px;" aria-expanded="false" class="nav nav-third-level collapse">
          <li>
            <%= link_to    backend_categories_path    do %>
            <i class="fa fa-list fa-fw"></i>
            Categories
            <% end %>
          </li>
          <li>
            <%= link_to     backend_sub_categories_path     do %>
            <i class="fa fa-list fa-fw"></i>
            Sub Categories
            <% end %>
          </li>

        </ul>
        <!-- /.nav-third-level -->
      </li>
    </ul>
  </div>
  <!-- /.sidebar-collapse -->
</div>